name: Hack-Illinois Challenge Pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build

    lint_and_format:
        runs-on: ubuntu-latest
        needs: build

        strategy:
            matrix:
                node-version: [12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn lint
            - run: yarn format

    test:
        runs-on: ubuntu-latest
        needs: build

        strategy:
            matrix:
                node-version: [12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn test

    deploy:
        name: Deploy
        needs: [build, lint_and_format, test]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: 12.x

        steps:
            - uses: actions/checkout@v2
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build